services:
  db-postgre:
    image: postgres:latest
    container_name: my-postgres-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgrepassword
      POSTGRES_DB: university_db
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql

  pgadmin-client:
    image: dpage/pgadmin4
    container_name: my-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "5050:80"
    depends_on:
      - db-postgre
